### PR TITLE
Unify logging

### LINKED ISSUE #5: Many "transport is closing" info log messages
**Describe the bug**
A lot of these "transport is closing" messages are logged. The adapter works but the logs get spammed.
```
$ kubectl -n newrelic-istio-adapter logs -l app.kubernetes.io/name=newrelic-istio-adapter
2019-09-17T23:47:28.939598Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:47:34.632641Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:47:38.941420Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:47:44.632182Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:47:48.937845Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:47:54.633491Z    info    transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:55912->127.0.0.1:56416: read: connection reset by peer
2019-09-17T23:47:54.633740Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:47:58.938496Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2019-09-17T23:48:04.632558Z    info    transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:55912->127.0.0.1:56488: read: connection reset by peer
2019-09-17T23:48:04.632620Z    info    transport: loopyWriter.run returning. connection error: desc = "transport is closing"
C02Z65TVLVDQ:helm-charts dstadler$
```

**To Reproduce**
1. Install adapter to k8s according to README
2. Check kubectl logs with `kubectl -n newrelic-istio-adapter logs -l app.kubernetes.io/name=newrelic-istio-adapter`

**Expected behavior**
The transport closing messages are not logged, no error messages are printed when adapter is functioning correctly.

**Version information (please complete the following information):**
 - newrelic-istio-adapter: 1.0.0
 - Kubernetes: v1.15
 - Istio: 1.2

### PR DESCRIPTION
**Pull request by MrAlias**
This unifies the adapter logging into a single package. It unifies the following sources of logging:

- The default [Istio log package](https://github.com/istio/pkg/tree/master/log). This is used for things not currently logged with the adapter logger, including gRPC logging. The default logger for this package overrides the gRPC logging package to unify into a single logging. To address #5, this source of logging needs to be configured and handled.
- The [New Relic telemetry pakcage](https://github.com/newrelic/newrelic-telemetry-sdk-go/blob/master/telemetry/config.go). This logs events interactions with the New Relic API and does so in a unique (different to the Istio logging) way.
- The [adapter's server logging](https://github.com/newrelic/newrelic-istio-adapter/blob/fa3dd151da59501b591f4002bca8ad1f87d9d982/server.go#L70). This is passed throughout this project.

This includes API breaking changes and will require a major version bump when released.

Closes #5

### CODE REVIEW

File: cmd/main.go [hunk 1]
```diff
@@ -38,7 +39,7 @@ var Version = "undefined"
 var (
 	portPtr          = kingpin.Flag("port", "port gRPC server listens on").Default("55912").OverrideDefaultFromEnvar("NEW_RELIC_PORT").Short('p').Int32()
 	clusterNamePtr   = kingpin.Flag("cluster-name", "Name of cluster where metrics come from").OverrideDefaultFromEnvar("NEW_RELIC_CLUSTER_NAME").String()
-	debugPtr         = kingpin.Flag("debug", "enable debug logging").OverrideDefaultFromEnvar("NEW_RELIC_DEBUG").Short('d').Bool()
+	logLevelPtr      = kingpin.Flag("log-level", "set logging level").OverrideDefaultFromEnvar("NEW_RELIC_LOG_LEVEL").Default("error").Enum(log.Levels()...)
```
Comment (kdef-nr) [inline cmd/main.go:42]: Should update the example command in DEVELOPMENT.md to use this flag instead of `--debug`

Comment (kdef-nr) [reply cmd/main.go:42]: It would be nice to know what other values `--log-level` can be set to other than `error`

Comment (kdef-nr) [reply cmd/main.go:42]: Actually the error message is pretty clear if you specify anything unexpected, I'm fine leaving the help message as is or adding the allowed values to it.
```
main: error: enum value must be one of fatal,none,debug,info,warn,error, got 'help', try --help
```

File: log/default.go [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+	"encoding/json"
+
+	"github.com/newrelic/newrelic-telemetry-sdk-go/telemetry"
+	iLog "istio.io/pkg/log"
+)
+
+const (
+	// AdapterScopeName is the default logging scope name for this adapter.
+	AdapterScopeName       = "newrelic"
+	defaultOutputLevel     = ErrorLevel
```
Comment (kdef-nr) [inline log/default.go:13]: Since `error` is the default output we should update this line in the DEVELOPMENT.md
```
The newrelic-istio-adapter should output activity to STDOUT signifying that metrics have been captured and sent to New Relic.
```
No output is expected now if things are working correctly

Comment (kdef-nr) [reply log/default.go:13]: Should also clarify this line in the README.md
```
The logs of Mixer and the newrelic-istio-adapter in Kubernetes should show activity or errors.
```

File: log/level.go [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+	// DebugLevel signifies all messages with debug level and above should be logged.
+	DebugLevel
+
+	// InfoLevel signifies all messages with info level and above should be logged.
+	InfoLevel
+
+	// WarnLevel signifies all messages with warn level and above should be logged.
+	WarnLevel
+
+	// ErrorLevel signifies all messages with fatal level and above should be logged.
```
Comment (kdef-nr) [inline log/level.go]:
```suggestion
	// ErrorLevel signifies all messages with error level and above should be logged.
```

File: metric/handler.go [hunk 4]
```diff
@@ -23,13 +23,11 @@ import (
 	"github.com/newrelic/newrelic-istio-adapter/config"
 	"github.com/newrelic/newrelic-istio-adapter/convert"
 	"github.com/newrelic/newrelic-telemetry-sdk-go/telemetry"
-	"istio.io/istio/mixer/pkg/adapter"
```
Comment (kdef-nr) [inline metric/handler.go:26]: nice

File: server.go [hunk 5]
```diff
@@ -65,9 +61,7 @@ var (
 
 // NewServer creates a new Mixer metric handling server.
 func NewServer(addr string, h *telemetry.Harvester, grpcOpt ...grpc.ServerOption) (*Server, error) {
-	gp := pool.NewGoroutinePool(5, false)
```
Comment (kdef-nr) [inline server.go:68]: Looks like this was never actually used before, other than to create a `NewEnv`, is that correct?

File: cmd/main.go (hunk 1 above)
Comment (MrAlias) [reply cmd/main.go:42]: @kdef-nr : w/r/t printing the `--log-level` options I agree. It is something inherent in `kingpin` unfortunately. I was thinking of transitioning to `cobra` (which Istio uses), but it seemed like a larger thing we can tackle if deemed necessary later on.

File: server.go (hunk 5 above)
Comment (MrAlias) [reply server.go:68]: Correct.

File: log/default.go (hunk 2 above)
Comment (MrAlias) [reply log/default.go:13]: Good catches :+1:

**Review by kdef-nr — APPROVED** [review]
👍
